services:

  app:
    build: .
    environment:
      DATABASE_ENGINE: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}
    ports:
      - 8002:80
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
#    ports:
#      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data:
